# Change these first
owner: mrays # Your GitHub organization or username, where this repository lives
repo: status.exputra.com # The name of this repository

sites:
    # IDC 1
  - name: Indonesia Coconuts (24 Juni 2024)
    url: https://indonesiacoconuts.com
  - name: Binuang Sakti (05 Agustus 2024)
    url: https://binuangsaktiperkasa.com/
    # RW STID 1
  - name: Global Intl Logistics (14 Juli 2024)
    url: https://globalintllogistics.com
  - name: Hinggil Spices (09 Oktober 2024)
    url: https://hinggil-spices.com
  - name: Sahabat Tukang (12 Mei 2024)
    url: https://sahabattukang.id
  - name: Siputra Digital (24 Juni 2024)
    url: https://siputra.digital/
    # RW JWT
  - name: Jasa WC Terdekat (05 Juni 2024)
    url: https://jasasedotwcterdekat.id/
  - name: Sumur Bor (04 Juni 2024)
    url: https://sumur-bor.com/
  - name: Kamba Jaya Industri (17 November 2024)
    url: https://kambajayaindustri.com/
  - name: Fajarindo Buana Ekspress (12 Desember 2024)
    url: https://pt.fajarindobuanaexpress.com/
  - name: Aksa Jasa Global (06 Desember 2024)
    url: https://aksajasaglobal.com/
  - name: Factory Bagan Citra Lestari (13 November 2024)
    url: https://factorybagancitralestari.com
    # VPS
  - name: Jasa Pipa Mampet (22 Desember 2024)
    url: https://jasapipamampetkediri.site/
  - name: Jasa Pipa Mampet 2 (22 Januari 2025)
    url: https://jasapipamampettulungagung.my.id/
    # Herisa Host
  - name: Herisa.id (22 Februari 2024)
    url: https://herisa.id
    # Herisa Host
  - name: Muslimin Indonesia Tour (26 Januari 2026)
    url: https://muslimindonesiatours.com
  - name: Askatama (1 Januari 2025/1)
    url: https://askatama.biz.id
  - name: Sunnahstori (03 Februari 2025)
    url: https://sunnahstori.com
  - name: Sedot WC Dua Putri (26 Desember 2025)
    url: https://sedotwcduaputri.my.id

status-website:
  cname: status.exputra.com
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name ther
  # baseUrl: /your-repo-name
  logoUrl: https://exputra.com/wp-content/uploads/2022/06/logoe-167x65.png
  name: Status
  introTitle: "**eXputra Server Monitor**"
  introMessage: Get Online Stay Online
  navbar:
    - title: Status
      href: /
i18n:
  footer: This page is Monitoring for Server, powered by eXputra Designs
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
