# Change these first
owner: mrays # Your GitHub organization or username, where this repository lives
repo: status.exputra.com # The name of this repository

sites:
    # IDC 1
  - name: Indonesia Coconuts
    url: https://indonesiacoconuts.com
  - name: Binuang Sakti
    url: https://binuangsaktiperkasa.com/
    # RW STID 1
  - name: Global Intl Logistics
    url: https://globalintllogistics.com
  - name: Hinggil Spices
    url: https://hinggil-spices.com
  - name: Sahabat Tukang
    url: https://sahabattukang.id
  - name: Siputra Digital
    url: https://siputra.digital/
    # RW JWT
  - name: Jasa WC 1
    url: https://jasasedotwcterdekat.id/
  - name: Sumur Bor
    url: https://sumur-bor.com/
  - name: Kamba Jaya Industri (2024-11-18)
    url: https://kambajayaindustri.com/
  - name: Fajarindo Buana Ekspress *2024-12-13*
    url: https://pt.fajarindobuanaexpress.com/
    
    
    # VPS
  - name: Jasa Pipa Mampet
    url: https://jasapipamampetkediri.site/
  - name: Sumur Bor
    url: https://sumur-bor.com/

status-website:
  cname: status.exputra.com
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name ther
  # baseUrl: /your-repo-name
  logoUrl: https://exputra.com/wp-content/uploads/2022/06/logoe-167x65.png
  name: 
  introTitle: "**eXputra Server Monitor**"
  introMessage: Get Online Stay Online
  navbar:
    - title: Status
      href: /
i18n:
  footer: This page is Monitoring for Server, powered by eXputra Designs
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
